C /etc/drivers/neuron-inf1.toml
C /etc/drivers/neuron-latest.toml
R __PREFIX__/lib/modules/__KERNEL_VERSION__/kernel/drivers/neuron/neuron_2_21 - - - - -
d __PREFIX__/lib/modules/__KERNEL_VERSION__/kernel/drivers/neuron/neuron_2_21 0755 root root - -
R __PREFIX__/lib/modules/__KERNEL_VERSION__/kernel/drivers/neuron/neuron_latest - - - - -
d __PREFIX__/lib/modules/__KERNEL_VERSION__/kernel/drivers/neuron/neuron_latest 0755 root root - -
